# Generated by Django 4.2.23 on 2025-09-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('page_order', models.IntegerField(help_text='Definition of the order each page appears in the application.', verbose_name='order of page in the application')),
                ('page_url', models.CharField(help_text='The URL of the page, in Django terminology.', max_length=80, verbose_name='django URL for the page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
