# Generated by Django 4.2.23 on 2025-09-18 11:51

import pendulum

from django.db import migrations

initial_applicationpage = {
    "app:get_ready": {'page_order': 1},
    "app:account": {'page_order': 2},
    "app:address": {'page_order': 3},
    "app:household": {'page_order': 4},
    "app:household_members": {'page_order': 5},
    "app:programs": {'page_order': 6},
    "app:files": {'page_order': 7},
}


def apply_fill_applicationpage(apps, schema_editor):
    ApplicationPage = apps.get_model('ref', 'applicationpage')

    now_time = pendulum.now()

    ApplicationPage.objects.bulk_create([
        ApplicationPage(
            created_at=now_time,
            modified_at=now_time,
            page_order=vl['page_order'],
            page_url=ky,
            ) for ky, vl in initial_applicationpage.items()
    ])


def revert_fill_applicationpage(apps, schema_editor):
    ApplicationPage = apps.get_model('ref', 'applicationpage')

    ApplicationPage.objects.filter(
        page_url__in=initial_applicationpage.keys()
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0002_applicationpage'),
    ]

    operations = [
        migrations.RunPython(
            code=apply_fill_applicationpage,
            reverse_code=revert_fill_applicationpage,
        ),
    ]
