# Generated by Django 5.2.7 on 2025-12-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0003_fill_applicationpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqprogram',
            name='additional_external_form_link',
            field=models.CharField(blank=True, help_text="Link to an external form for additional information needed by the program, if applicable (leave blank for no form). Note that this must start with 'https://' or 'http://', and the target form needs to have a way for the program coordinator to link its information to the Get FoCo user.", max_length=5000),
        ),
        migrations.AlterField(
            model_name='iqprogram',
            name='learn_more_link',
            field=models.CharField(help_text="Link for the user to learn more about the program. Note that this must start with 'https://' or 'http://'.", max_length=5000),
        ),
    ]
