# Generated by Django 6.0.5 on 2026-05-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0004_iqprogram_additional_external_form_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(db_default='', default='', help_text='House number and street name.', max_length=200, verbose_name='street address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, db_default='', default='', help_text='Leave blank if not applicable.', max_length=200, verbose_name='apt, suite, etc.'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_verified',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(db_default='', default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='eligibilityprogram',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True, help_text='Designates whether the program is in-use or not. Unselect this instead of deleting programs.'),
        ),
        migrations.AlterField(
            model_name='iqprogram',
            name='enable_autoapply',
            field=models.BooleanField(db_default=False, default=False, help_text='Designates whether the program should automatically apply new users who are eligible.'),
        ),
        migrations.AlterField(
            model_name='iqprogram',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True, help_text='Designates whether the program is in-use or not. Unselect this instead of deleting programs.'),
        ),
        migrations.AlterField(
            model_name='iqprogram',
            name='requires_is_city_covered',
            field=models.BooleanField(db_default=True, default=True, help_text="Designates whether the user's eligibility address is required to be 'covered by the City' to be eligible. 'City coverage' is always True for addresses within the GMA, otherwise it's determined by the Get FoCo administrators."),
        ),
        migrations.AlterField(
            model_name='iqprogram',
            name='requires_is_in_gma',
            field=models.BooleanField(db_default=True, default=True, help_text="Designates whether the user's eligibility address is required to be in the GMA to be eligible."),
        ),
    ]
