# Generated by Django 6.0.5 on 2026-05-21 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_iqprogram_is_enrolled'),
        ('ref', '0005_alter_address_address1_alter_address_address2_and_more'),
        ('users', '0007_alter_user_duration_at_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='AddressRef',
        ),
        migrations.RenameModel(
            old_name='EligibilityProgram',
            new_name='EligibilityProgramRef',
        ),
        migrations.RenameModel(
            old_name='IQProgram',
            new_name='IQProgramRef',
        ),
    ]
