# Generated by Django 6.0.5 on 2026-06-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0006_rename_address_addressref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityprogramref',
            name='bi_icon',
            field=models.CharField(help_text='Bootstrap icon to use, when rendering the program', max_length=50, null=True),
        ),
    ]
