# Generated by Django 4.1 on 2023-05-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="household",
            name="ami_range_max",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="ami_range_min",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=3, null=True
            ),
        ),
    ]
