# Generated by Django 4.1 on 2023-05-12 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_household_ami_range_max_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="householdmembers",
            name="created_at_init_temp",
        ),
        migrations.RemoveField(
            model_name="householdmembers",
            name="modified_at_init_temp",
        ),
    ]
