# Generated by Django 4.1.8 on 2023-06-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_delete_addresslookup_delete_futureemail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_eligibility_address_updated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="is_mailing_address_updated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_updated",
            field=models.BooleanField(default=False),
        ),
    ]
