# Generated by Django 4.1.8 on 2023-06-05 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_userhist_addresshist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address", name="is_eligibility_address_updated",
        ),
        migrations.RemoveField(
            model_name="address", name="is_mailing_address_updated",
        ),
        migrations.AddField(
            model_name="address",
            name="is_updated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="householdmembers",
            name="is_updated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="householdhist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="household_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="HouseholdMembersHist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("historical_values", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="householdmembers_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
