# Generated by Django 4.1.8 on 2023-06-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_userhist_addresshist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="household",
            old_name="ami_range_max",
            new_name="income_as_fraction_of_ami",
        ),
        migrations.RemoveField(model_name="household", name="ami_range_min",),
    ]
