# Generated by Django 4.1.8 on 2023-12-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_iqprogram_has_renewed_user_last_renewal_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqprogramrd',
            name='renewal_interval',
            field=models.IntegerField(null=True),
        ),
    ]
