# Generated by Django 4.1.8 on 2023-12-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_iqprogramrd_renewal_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_renewed_at',
            new_name='last_completed_at',
        ),
    ]
