# Generated by Django 4.1.8 on 2023-12-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_last_renewed_at_user_last_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iqprogram',
            name='has_renewed',
        ),
        migrations.AddField(
            model_name='user',
            name='renewal_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
