# Generated by Django 4.1.8 on 2024-03-18 14:49

from django.db import migrations

from django_q.models import Schedule

SCHEDULE_NAME = 'Run Renewal Task'

def apply_migration(apps, schema_editor):
    # Get the schedule, modify the cluster, and resave
    sch = Schedule.objects.filter(name=SCHEDULE_NAME).get()
    sch.cluster = 'long'
    sch.save()


def revert_migration(apps, schema_editor):
    # Get the schedule, modify the cluster, and resave
    sch = Schedule.objects.filter(name=SCHEDULE_NAME).get()
    sch.cluster = 'DjangORM'
    sch.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_change_django_q_renewal_schedule"),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
