# Generated by Django 4.1.8 on 2024-03-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_change_django_q_renewal_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_application_action",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
