# Generated by Django 4.1.8 on 2024-04-21 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_change_django_q_renewal_schedule_again"),
        ("app", "0019_rename_renewal_interval_month_iqprogramrd_renewal_interval_year"),
    ]

    operations = []
