# Generated by Django 4.1.8 on 2024-04-12 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

from app.models import (
    User,
    Address,
    AddressRD,
    Household,
    HouseholdMembers,
    EligibilityProgram,
    EligibilityProgramRD,
    IQProgram,
    IQProgramRD,
    Feedback,
    Admin as AppAdmin,
)


def apply_admin_group(apps, schema_editor):
    # Define the auth group. Note that this migration will override the
    # permissions if a group exists with this name
    admin_group, _ = Group.objects.get_or_create(name='admin_program')

    # Define the list of permissions (from testing)
    permissions_list = [
        Permission.objects.get(
            codename='change_user',
            content_type=ContentType.objects.get_for_model(User),
        ),
        Permission.objects.get(
            codename='view_user',
            content_type=ContentType.objects.get_for_model(User),
        ),
        Permission.objects.get(
            codename='view_admin',
            content_type=ContentType.objects.get_for_model(AppAdmin),
        ),
        Permission.objects.get(
            codename='change_admin',
            content_type=ContentType.objects.get_for_model(AppAdmin),
        ),
        Permission.objects.get(
            codename='view_address',
            content_type=ContentType.objects.get_for_model(Address),
        ),
        Permission.objects.get(
            codename='change_addressrd',
            content_type=ContentType.objects.get_for_model(AddressRD),
        ),
        Permission.objects.get(
            codename='view_addressrd',
            content_type=ContentType.objects.get_for_model(AddressRD),
        ),
        Permission.objects.get(
            codename='change_household',
            content_type=ContentType.objects.get_for_model(Household),
        ),
        Permission.objects.get(
            codename='view_household',
            content_type=ContentType.objects.get_for_model(Household),
        ),
        Permission.objects.get(
            codename='view_householdmembers',
            content_type=ContentType.objects.get_for_model(HouseholdMembers),
        ),
        Permission.objects.get(
            codename='change_eligibilityprogram',
            content_type=ContentType.objects.get_for_model(EligibilityProgram),
        ),
        Permission.objects.get(
            codename='view_eligibilityprogram',
            content_type=ContentType.objects.get_for_model(EligibilityProgram),
        ),
        Permission.objects.get(
            codename='add_eligibilityprogramrd',
            content_type=ContentType.objects.get_for_model(EligibilityProgramRD),
        ),
        Permission.objects.get(
            codename='change_eligibilityprogramrd',
            content_type=ContentType.objects.get_for_model(EligibilityProgramRD),
        ),
        Permission.objects.get(
            codename='view_eligibilityprogramrd',
            content_type=ContentType.objects.get_for_model(EligibilityProgramRD),
        ),
        Permission.objects.get(
            codename='view_iqprogram',
            content_type=ContentType.objects.get_for_model(IQProgram),
        ),
        Permission.objects.get(
            codename='add_iqprogramrd',
            content_type=ContentType.objects.get_for_model(IQProgramRD),
        ),
        Permission.objects.get(
            codename='change_iqprogramrd',
            content_type=ContentType.objects.get_for_model(IQProgramRD),
        ),
        Permission.objects.get(
            codename='view_iqprogramrd',
            content_type=ContentType.objects.get_for_model(IQProgramRD),
        ),
        Permission.objects.get(
            codename='view_feedback',
            content_type=ContentType.objects.get_for_model(Feedback),
        ),
        Permission.objects.get(
            codename='delete_eligibilityprogram',
            content_type=ContentType.objects.get_for_model(EligibilityProgram),
        ),
    ]

    # Set the permissions for the group
    admin_group.permissions.set(permissions_list)


def apply_income_group(apps, schema_editor):
    # Define the auth group. Note that this migration will override the
    # permissions if a group exists with this name
    income_group, _ = Group.objects.get_or_create(name='income_verification_staff')

    # Define the list of permissions (from testing)
    permissions_list = [
        Permission.objects.get(
            codename='change_user',
            content_type=ContentType.objects.get_for_model(User),
        ),
        Permission.objects.get(
            codename='view_user',
            content_type=ContentType.objects.get_for_model(User),
        ),
        Permission.objects.get(
            codename='view_admin',
            content_type=ContentType.objects.get_for_model(AppAdmin),
        ),
        Permission.objects.get(
            codename='change_admin',
            content_type=ContentType.objects.get_for_model(AppAdmin),
        ),
        Permission.objects.get(
            codename='view_address',
            content_type=ContentType.objects.get_for_model(Address),
        ),
        Permission.objects.get(
            codename='change_addressrd',
            content_type=ContentType.objects.get_for_model(AddressRD),
        ),
        Permission.objects.get(
            codename='view_addressrd',
            content_type=ContentType.objects.get_for_model(AddressRD),
        ),
        Permission.objects.get(
            codename='change_eligibilityprogram',
            content_type=ContentType.objects.get_for_model(EligibilityProgram),
        ),
        Permission.objects.get(
            codename='view_eligibilityprogram',
            content_type=ContentType.objects.get_for_model(EligibilityProgram),
        ),
        Permission.objects.get(
            codename='change_household',
            content_type=ContentType.objects.get_for_model(Household),
        ),
        Permission.objects.get(
            codename='view_household',
            content_type=ContentType.objects.get_for_model(Household),
        ),
        Permission.objects.get(
            codename='view_householdmembers',
            content_type=ContentType.objects.get_for_model(HouseholdMembers),
        ),
        Permission.objects.get(
            codename='view_iqprogram',
            content_type=ContentType.objects.get_for_model(IQProgram),
        ),
    ]

    # Set the permissions for the group
    income_group.permissions.set(permissions_list)


class Migration(migrations.Migration):

    replaces = [('app', '0020_alter_address_options_alter_addressrd_options_and_more'), ('app', '0021_alter_address_eligibility_address'), ('app', '0022_alter_addressrd_is_city_covered_and_more'), ('app', '0023_alter_iqprogram_user'), ('app', '0024_alter_eligibilityprogram_options_and_more'), ('app', '0025_admin'), ('app', '0026_fill_app_admin'), ('app', '0027_alter_admin_options_and_more'), ('app', '0028_add_permissions_groups'), ('app', '0029_alter_admin_options_alter_feedback_options_and_more'), ('app', '0030_alter_permissions_group')]

    dependencies = [
        ('app', '0019_rename_renewal_interval_month_iqprogramrd_renewal_interval_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='addressrd',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='eligibilityprogramrd',
            options={'verbose_name': 'eligibility program', 'verbose_name_plural': 'eligibility programs'},
        ),
        migrations.AlterModelOptions(
            name='household',
            options={'verbose_name': 'household', 'verbose_name_plural': 'household'},
        ),
        migrations.AlterModelOptions(
            name='householdmembers',
            options={'verbose_name': 'household member', 'verbose_name_plural': 'household members'},
        ),
        migrations.AlterModelOptions(
            name='iqprogram',
            options={'verbose_name': 'IQ program', 'verbose_name_plural': 'IQ programs'},
        ),
        migrations.AlterModelOptions(
            name='iqprogramrd',
            options={'verbose_name': 'IQ program', 'verbose_name_plural': 'IQ programs'},
        ),
        migrations.AlterField(
            model_name='address',
            name='eligibility_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eligibility_user', to='app.addressrd'),
        ),
        migrations.AlterField(
            model_name='addressrd',
            name='is_city_covered',
            field=models.BooleanField(default=None, help_text='Designates whether an address is eligible for benefits. This can be altered if the address is outside the GMA.', null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='duration_at_address',
            field=models.CharField(choices=[('More than 3 Years', 'More than 3 Years'), ('1 to 3 Years', '1 to 3 Years'), ('Less than a Year', 'Less than a Year')], max_length=200),
        ),
        migrations.AlterField(
            model_name='household',
            name='is_income_verified',
            field=models.BooleanField(default=False, help_text='Designates whether an applicant has had their income verified.', verbose_name='income has been verified'),
        ),
        migrations.AlterField(
            model_name='household',
            name='number_persons_in_household',
            field=models.IntegerField(default=1, help_text='Number of persons in the household.', verbose_name='household size'),
        ),
        migrations.AlterField(
            model_name='household',
            name='rent_own',
            field=models.CharField(choices=[('rent', 'Rent'), ('own', 'Own')], help_text='Designates whether the applicant rents or owns their primary residence.', max_length=200, verbose_name='rent or own'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="Designates whether the user is marked as 'archived'."),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_action_notification_at',
            field=models.DateTimeField(blank=True, help_text='The latest time a notification was sent because of or requesting user action.', null=True, verbose_name='Last notification based on user action'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_completed_at',
            field=models.DateTimeField(blank=True, help_text='The latest time the user completed an application/renewal.', null=True),
        ),
        migrations.AlterField(
            model_name='iqprogram',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iq_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='eligibilityprogram',
            options={'verbose_name': 'user eligibility program', 'verbose_name_plural': 'user eligibility programs'},
        ),
        migrations.AlterModelOptions(
            name='iqprogram',
            options={'verbose_name': 'user IQ program', 'verbose_name_plural': 'user IQ programs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='last_action_notification_at',
            field=models.DateTimeField(blank=True, help_text='The latest time a notification was sent because of or requesting user action.', null=True, verbose_name='Last user action notification'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('awaiting_user_response', models.BooleanField(default=False, help_text='Designates that the admin is waiting for a user to respond to a request made separate from this platform. This is used only to filter income-verification applicants.')),
            ],
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'administration'},
        ),
        migrations.RemoveField(
            model_name='iqprogramrd',
            name='req_is_city_covered',
        ),
        migrations.RemoveField(
            model_name='iqprogramrd',
            name='req_is_in_gma',
        ),
        migrations.AddField(
            model_name='iqprogramrd',
            name='requires_is_city_covered',
            field=models.BooleanField(default=False, help_text="Designates whether the user's eligibility address is required to be 'covered by the City' to be eligible. 'City coverage' is always True for addresses within the GMA, otherwise it's determined by the Get FoCo administrators."),
        ),
        migrations.AddField(
            model_name='iqprogramrd',
            name='requires_is_in_gma',
            field=models.BooleanField(default=False, help_text="Designates whether the user's eligibility address is required to be in the GMA to be eligible."),
        ),
        migrations.AlterField(
            model_name='eligibilityprogramrd',
            name='ami_threshold',
            field=models.DecimalField(decimal_places=2, help_text="Income threshold of the program, as a fraction of AMI (e.g. '0.30' == 30% of AMI)", max_digits=3),
        ),
        migrations.AlterField(
            model_name='eligibilityprogramrd',
            name='friendly_description',
            field=models.CharField(help_text='The user-friendly description of the program. This will be visible to users on the platform.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='eligibilityprogramrd',
            name='friendly_name',
            field=models.CharField(help_text='The user-friendly name of the program. This will be visible to users on the platform.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='eligibilityprogramrd',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the program is in-use or not. Unselect this instead of deleting programs.'),
        ),
        migrations.AlterField(
            model_name='eligibilityprogramrd',
            name='program_name',
            field=models.CharField(help_text='Program reference name within the platform. Must be lowercase with no spaces.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='iqprogramrd',
            name='ami_threshold',
            field=models.DecimalField(decimal_places=2, help_text="Income threshold of the program, as a fraction of AMI (e.g. '0.30' == 30% of AMI).", max_digits=3),
        ),
        migrations.AlterField(
            model_name='iqprogramrd',
            name='enable_autoapply',
            field=models.BooleanField(default=False, help_text='Designates whether the program should automatically apply new users who are eligible.'),
        ),
        migrations.AlterField(
            model_name='iqprogramrd',
            name='friendly_category',
            field=models.CharField(help_text='The user-friendly category this program is in. This will be visible to users on the platform.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='iqprogramrd',
            name='friendly_description',
            field=models.CharField(help_text='The user-friendly description of the program. This will be visible to users on the platform.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='iqprogramrd',
            name='friendly_eligibility_review_period',
            field=models.CharField(help_text="The estimated time it will take to review a user's application. This will be visible to users on the platform.", max_length=5000),
        ),
        migrations.AlterField(
            model_name='iqprogramrd',
            name='friendly_name',
            field=models.CharField(help_text='The user-friendly name of the program. This will be visible to users on the platform.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='iqprogramrd',
            name='friendly_supplemental_info',
            field=models.CharField(help_text='Any supplmental information to display to the user.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='iqprogramrd',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the program is in-use or not. Unselect this instead of deleting programs.'),
        ),
        migrations.AlterField(
            model_name='iqprogramrd',
            name='learn_more_link',
            field=models.CharField(help_text='Link for the user to learn more about the program.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='iqprogramrd',
            name='program_name',
            field=models.CharField(help_text='Program reference name within the platform. Must be lowercase with no spaces.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='iqprogramrd',
            name='renewal_interval_year',
            field=models.IntegerField(help_text='The frequency at which a user needs to renew their application for this IQ program. Leave blank for a non-renewing (lifetime-enrollment) program.', null=True, verbose_name='renewal interval in years'),
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'administration', 'verbose_name_plural': 'administration'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'feedback', 'verbose_name_plural': 'feedback'},
        ),
        migrations.AddField(
            model_name='admin',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Notes pertaining to this user, for internal use. This field is not visible to applicants.'),
        ),
        # Define no operation for reversion. Removing permissions groups will
        # reset all applied users, so the 'apply' procedures instead overwrite
        # permissions on any existing groups
        migrations.RunPython(apply_admin_group, migrations.RunPython.noop),
        migrations.RunPython(apply_income_group, migrations.RunPython.noop),
    ]
