# Generated by Django 4.1.8 on 2024-03-21 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_rename_renewal_interval_month_iqprogramrd_renewal_interval_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "address", "verbose_name_plural": "addresses"},
        ),
        migrations.AlterModelOptions(
            name="addressrd",
            options={"verbose_name": "address", "verbose_name_plural": "addresses"},
        ),
        migrations.AlterModelOptions(
            name="eligibilityprogram",
            options={
                "verbose_name": "eligibility program",
                "verbose_name_plural": "eligibility programs",
            },
        ),
        migrations.AlterModelOptions(
            name="eligibilityprogramrd",
            options={
                "verbose_name": "eligibility program",
                "verbose_name_plural": "eligibility programs",
            },
        ),
        migrations.AlterModelOptions(
            name="household",
            options={"verbose_name": "household", "verbose_name_plural": "household"},
        ),
        migrations.AlterModelOptions(
            name="householdmembers",
            options={
                "verbose_name": "household member",
                "verbose_name_plural": "household members",
            },
        ),
        migrations.AlterModelOptions(
            name="iqprogram",
            options={
                "verbose_name": "IQ program",
                "verbose_name_plural": "IQ programs",
            },
        ),
        migrations.AlterModelOptions(
            name="iqprogramrd",
            options={
                "verbose_name": "IQ program",
                "verbose_name_plural": "IQ programs",
            },
        ),
    ]
