# Generated by Django 4.1.8 on 2024-03-29 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_alter_address_options_alter_addressrd_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="eligibility_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="eligibility_user",
                to="app.addressrd",
            ),
        ),
    ]
