# Generated by Django 4.1.8 on 2024-03-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_alter_address_eligibility_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressrd",
            name="is_city_covered",
            field=models.BooleanField(
                default=None,
                help_text="Designates whether an address is eligible for benefits. This can be altered if the address is outside the GMA.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="duration_at_address",
            field=models.CharField(
                choices=[
                    ("More than 3 Years", "More than 3 Years"),
                    ("1 to 3 Years", "1 to 3 Years"),
                    ("Less than a Year", "Less than a Year"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="is_income_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether an applicant has had their income verified.",
                verbose_name="income has been verified",
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="number_persons_in_household",
            field=models.IntegerField(
                default=1,
                help_text="Number of persons in the household.",
                verbose_name="household size",
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="rent_own",
            field=models.CharField(
                choices=[("rent", "Rent"), ("own", "Own")],
                help_text="Designates whether the applicant rents or owns their primary residence.",
                max_length=200,
                verbose_name="rent or own",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user is marked as 'archived'.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_action_notification_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The latest time a notification was sent because of or requesting user action.",
                null=True,
                verbose_name="Last notification based on user action",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The latest time the user completed an application/renewal.",
                null=True,
            ),
        ),
    ]
