# Generated by Django 4.1.8 on 2024-04-01 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_alter_addressrd_is_city_covered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iqprogram",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="iq_programs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
