# Generated by Django 4.1.8 on 2024-04-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_alter_iqprogram_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eligibilityprogram",
            options={
                "verbose_name": "user eligibility program",
                "verbose_name_plural": "user eligibility programs",
            },
        ),
        migrations.AlterModelOptions(
            name="iqprogram",
            options={
                "verbose_name": "user IQ program",
                "verbose_name_plural": "user IQ programs",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="last_action_notification_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The latest time a notification was sent because of or requesting user action.",
                null=True,
                verbose_name="Last user action notification",
            ),
        ),
    ]
