# Generated by Django 4.1.8 on 2024-04-04 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0024_alter_eligibilityprogram_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="admin",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "awaiting_user_response",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that the admin is waiting for a user to respond to a request made separate from this platform. This is used only to filter income-verification applicants.",
                    ),
                ),
            ],
        ),
    ]
