# Generated by Django 4.1.8 on 2024-04-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0026_fill_app_admin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admin",
            options={"verbose_name": "administration"},
        ),
        migrations.RemoveField(
            model_name="iqprogramrd",
            name="req_is_city_covered",
        ),
        migrations.RemoveField(
            model_name="iqprogramrd",
            name="req_is_in_gma",
        ),
        migrations.AddField(
            model_name="iqprogramrd",
            name="requires_is_city_covered",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user's eligibility address is required to be 'covered by the City' to be eligible. 'City coverage' is always True for addresses within the GMA, otherwise it's determined by the Get FoCo administrators.",
            ),
        ),
        migrations.AddField(
            model_name="iqprogramrd",
            name="requires_is_in_gma",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user's eligibility address is required to be in the GMA to be eligible.",
            ),
        ),
        migrations.AlterField(
            model_name="eligibilityprogramrd",
            name="ami_threshold",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Income threshold of the program, as a fraction of AMI (e.g. '0.30' == 30% of AMI)",
                max_digits=3,
            ),
        ),
        migrations.AlterField(
            model_name="eligibilityprogramrd",
            name="friendly_description",
            field=models.CharField(
                help_text="The user-friendly description of the program. This will be visible to users on the platform.",
                max_length=5000,
            ),
        ),
        migrations.AlterField(
            model_name="eligibilityprogramrd",
            name="friendly_name",
            field=models.CharField(
                help_text="The user-friendly name of the program. This will be visible to users on the platform.",
                max_length=5000,
            ),
        ),
        migrations.AlterField(
            model_name="eligibilityprogramrd",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether the program is in-use or not. Unselect this instead of deleting programs.",
            ),
        ),
        migrations.AlterField(
            model_name="eligibilityprogramrd",
            name="program_name",
            field=models.CharField(
                help_text="Program reference name within the platform. Must be lowercase with no spaces.",
                max_length=40,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="iqprogramrd",
            name="ami_threshold",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Income threshold of the program, as a fraction of AMI (e.g. '0.30' == 30% of AMI).",
                max_digits=3,
            ),
        ),
        migrations.AlterField(
            model_name="iqprogramrd",
            name="enable_autoapply",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the program should automatically apply new users who are eligible.",
            ),
        ),
        migrations.AlterField(
            model_name="iqprogramrd",
            name="friendly_category",
            field=models.CharField(
                help_text="The user-friendly category this program is in. This will be visible to users on the platform.",
                max_length=5000,
            ),
        ),
        migrations.AlterField(
            model_name="iqprogramrd",
            name="friendly_description",
            field=models.CharField(
                help_text="The user-friendly description of the program. This will be visible to users on the platform.",
                max_length=5000,
            ),
        ),
        migrations.AlterField(
            model_name="iqprogramrd",
            name="friendly_eligibility_review_period",
            field=models.CharField(
                help_text="The estimated time it will take to review a user's application. This will be visible to users on the platform.",
                max_length=5000,
            ),
        ),
        migrations.AlterField(
            model_name="iqprogramrd",
            name="friendly_name",
            field=models.CharField(
                help_text="The user-friendly name of the program. This will be visible to users on the platform.",
                max_length=5000,
            ),
        ),
        migrations.AlterField(
            model_name="iqprogramrd",
            name="friendly_supplemental_info",
            field=models.CharField(
                help_text="Any supplmental information to display to the user.",
                max_length=5000,
            ),
        ),
        migrations.AlterField(
            model_name="iqprogramrd",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether the program is in-use or not. Unselect this instead of deleting programs.",
            ),
        ),
        migrations.AlterField(
            model_name="iqprogramrd",
            name="learn_more_link",
            field=models.CharField(
                help_text="Link for the user to learn more about the program.",
                max_length=5000,
            ),
        ),
        migrations.AlterField(
            model_name="iqprogramrd",
            name="program_name",
            field=models.CharField(
                help_text="Program reference name within the platform. Must be lowercase with no spaces.",
                max_length=40,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="iqprogramrd",
            name="renewal_interval_year",
            field=models.IntegerField(
                help_text="The frequency at which a user needs to renew their application for this IQ program. Leave blank for a non-renewing (lifetime-enrollment) program.",
                null=True,
                verbose_name="renewal interval in years",
            ),
        ),
    ]
