# Generated by Django 4.1.8 on 2024-04-09 20:15

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

from app.models import EligibilityProgram

# Define the auth group to add permissions to
admin_group, _ = Group.objects.get_or_create(name='admin_program')

# Define the list of permissions (from testing)
permissions = Permission.objects.get(
    codename='delete_eligibilityprogram',
    content_type=ContentType.objects.get_for_model(EligibilityProgram),
)


def alter_admin_group(apps, schema_editor):
    # Add the permissions for the group
    admin_group.permissions.add(permissions)


def remove_alter_admin_group(apps, schema_editor):
    # Remove the permissions for the group
    admin_group.permissions.remove(permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0029_alter_admin_options_alter_feedback_options_and_more"),
    ]

    operations = [
        migrations.RunPython(alter_admin_group, remove_alter_admin_group)
    ]
