# Generated by Django 4.1.8 on 2024-07-24 21:22

from django.db import migrations, models
import django.db.migrations.operations.special


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# app.migrations.0035_auto_20240722_1428

class Migration(migrations.Migration):

    replaces = [('app', '0031_merge_20240422_0637'), ('app', '0032_alter_addressrd_address1_alter_addressrd_address2'), ('app', '0033_alter_addressrd_is_city_covered'), ('app', '0034_alter_iqprogramrd_friendly_supplemental_info'), ('app', '0035_auto_20240722_1428')]

    dependencies = [
        ('app', '0020_merge_20240421_0832'),
        ('app', '0020_alter_address_options_alter_addressrd_options_and_more_squashed_0030_alter_permissions_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressrd',
            name='address1',
            field=models.CharField(default='', help_text='House number and street name.', max_length=200, verbose_name='street address'),
        ),
        migrations.AlterField(
            model_name='addressrd',
            name='address2',
            field=models.CharField(blank=True, default='', help_text='Leave blank if not applicable.', max_length=200, verbose_name='apt, suite, etc.'),
        ),
        migrations.AlterField(
            model_name='addressrd',
            name='is_city_covered',
            field=models.BooleanField(default=None, help_text='Designates whether an address is eligible for benefits. This can be altered by administrators if the address is outside the GMA.', null=True),
        ),
        migrations.AlterField(
            model_name='iqprogramrd',
            name='friendly_supplemental_info',
            field=models.CharField(help_text='Any supplemental information to display to the user.', max_length=5000),
        ),
        migrations.RunPython(
            code=app.migrations.0035_auto_20240722_1428.apply_income_group,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
