# Generated by Django 4.1.8 on 2024-07-20 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0032_alter_addressrd_address1_alter_addressrd_address2"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseholdNew",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_updated", models.BooleanField(default=False)),
                (
                    "is_income_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether an applicant has had their income verified.",
                        verbose_name="income has been verified",
                    ),
                ),
                (
                    "duration_at_address",
                    models.CharField(
                        choices=[
                            ("More than 3 Years", "More than 3 Years"),
                            ("1 to 3 Years", "1 to 3 Years"),
                            ("Less than a Year", "Less than a Year"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "income_as_fraction_of_ami",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=3, null=True
                    ),
                ),
                (
                    "rent_own",
                    models.CharField(
                        choices=[("rent", "Rent"), ("own", "Own")],
                        help_text="Designates whether the applicant rents or owns their primary residence.",
                        max_length=200,
                        verbose_name="rent or own",
                    ),
                ),
            ],
            options={
                "verbose_name": "household",
                "verbose_name_plural": "household",
            },
        ),
        migrations.CreateModel(
            name="HouseholdMembersNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=200)),
                ("birthdate", models.DateField()),
                ("identification_path", models.FileField(upload_to="")),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="app.householdnew",
                    ),
                ),
            ],
            options={
                "verbose_name": "household member",
                "verbose_name_plural": "household members",
            },
        ),
    ]
