# Generated by Django 4.1.8 on 2024-07-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0033_alter_addressrd_is_city_covered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iqprogramrd",
            name="friendly_supplemental_info",
            field=models.CharField(
                help_text="Any supplemental information to display to the user.",
                max_length=5000,
            ),
        ),
    ]
