# Generated by Django 4.1.8 on 2024-05-13 19:23

import pendulum

from django.db import migrations

from django_q.models import Schedule

SCHEDULE_NAME = 'Populate Renewal Cache'

def apply_migration(apps, schema_editor):
    # Add daily 'Send Renewal Email' schedule to Django-Q2
    Schedule.objects.create(
        # Name the schedule
        name=SCHEDULE_NAME,
        # Run the function
        func='app.tasks.populate_redis_cache',
        # Create a 'daily' schedule
        schedule_type=Schedule.DAILY,
        # Call the cluster specified by the Q_CLUSTER setting
        cluster='DJRedis',
        # DOES NOT REPEAT. This needs to be 'enabled' once online (generally by
        # setting repeats=-1 to repeat forever)
        repeats=0,
        # Set the next run to be at just before midnight yesterday in
        # America/Denver timezone (should continue to be just before the 'Run
        # Renewal Task' schedule)
        next_run=pendulum.yesterday(tz='America/Denver').add(hours=23, minutes=50),
    )



def revert_migration(apps, schema_editor):
    # Remove the schedule with the same name
    Schedule.objects.filter(name=SCHEDULE_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0033_change_django_q_renewal_schedule_again_again"),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
