# Generated by Django 4.1.8 on 2024-07-22 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0034_alter_iqprogramrd_friendly_supplemental_info"),
    ]

    operations = [
        # Define no operations (this is now a placeholder)
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
