# Generated by Django 4.1.8 on 2024-07-22 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

from app.models import (
    User,
    Address,
    AddressRD,
    Household,
    HouseholdMembers,
    EligibilityProgram,
    EligibilityProgramRD,
    IQProgram,
    IQProgramRD,
    Feedback,
    Admin as AppAdmin,
)


def apply_income_group(apps, schema_editor):
    # Define the auth group. Note that this migration will override the
    # permissions if a group exists with this name
    income_group, _ = Group.objects.get_or_create(name='income_verification_staff')

    # Define the list of permissions (from testing)
    permissions_list = [
        Permission.objects.get_or_create(
            codename='change_user',
            content_type=ContentType.objects.get_for_model(User),
        )[0],
        Permission.objects.get_or_create(
            codename='view_user',
            content_type=ContentType.objects.get_for_model(User),
        )[0],
        Permission.objects.get_or_create(
            codename='view_admin',
            content_type=ContentType.objects.get_for_model(AppAdmin),
        )[0],
        Permission.objects.get_or_create(
            codename='change_admin',
            content_type=ContentType.objects.get_for_model(AppAdmin),
        )[0],
        Permission.objects.get_or_create(
            codename='view_address',
            content_type=ContentType.objects.get_for_model(Address),
        )[0],
        Permission.objects.get_or_create(
            codename='change_addressrd',
            content_type=ContentType.objects.get_for_model(AddressRD),
        )[0],
        Permission.objects.get_or_create(
            codename='view_addressrd',
            content_type=ContentType.objects.get_for_model(AddressRD),
        )[0],
        Permission.objects.get_or_create(
            codename='view_eligibilityprogram',
            content_type=ContentType.objects.get_for_model(EligibilityProgram),
        )[0],
        Permission.objects.get_or_create(
            codename='change_household',
            content_type=ContentType.objects.get_for_model(Household),
        )[0],
        Permission.objects.get_or_create(
            codename='view_household',
            content_type=ContentType.objects.get_for_model(Household),
        )[0],
        Permission.objects.get_or_create(
            codename='view_householdmembers',
            content_type=ContentType.objects.get_for_model(HouseholdMembers),
        )[0],
        Permission.objects.get_or_create(
            codename='view_iqprogram',
            content_type=ContentType.objects.get_for_model(IQProgram),
        )[0],
    ]

    # Set the permissions for the group
    income_group.permissions.set(permissions_list)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0034_alter_iqprogramrd_friendly_supplemental_info"),
    ]

    operations = [
        # Define no operation for reversion. Removing permissions groups will
        # reset all applied users, so the 'apply' procedures instead overwrite
        # permissions on any existing groups
        migrations.RunPython(apply_income_group, migrations.RunPython.noop),
    ]
