# Generated by Django 4.1.8 on 2026-03-31 15:32

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

from app.models import HouseholdMembers

admin_group, _ = Group.objects.get_or_create(name='admin_program')

# Define the list of permissions (from testing)
permissions_list = [
    Permission.objects.get_or_create(
        codename='change_householdmembers',
        content_type=ContentType.objects.get_for_model(HouseholdMembers),
    )[0],
]


def apply_admin_group(apps, schema_editor):
    # Add each permission to the 'admin_group' group
    admin_group.permissions.add(*permissions_list)

def revert_admin_group(apps, schema_editor):
    # Remove each permission from the 'admin_group' group
    admin_group.permissions.remove(*permissions_list)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_iqprogramrd_additional_external_form_link_and_more'),
    ]

    operations = [
        migrations.RunPython(apply_admin_group, revert_admin_group),
    ]
