# Generated by Django 4.1.8 on 2026-07-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_update_admin_program_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iqprogramrd',
            name='additional_external_form_link',
            field=models.CharField(blank=True, help_text="Link to an external form for additional information needed by the program, if applicable (leave blank for no form). The program coordinator is responsible for this form and for linking form submissions to Get FoCo applicants. Note that this must start with 'https://' or 'http://'.", max_length=5000),
        ),
    ]
