# Generated by Django 4.1.8 on 2024-07-24 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0031_merge_20240422_0637_squashed_0035_auto_20240722_1428"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Admin",
            new_name="AppAdmin",
        ),
    ]
