# Generated by Django 4.1.8 on 2024-07-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0036_define_permissions_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iqprogramrd",
            name="requires_is_city_covered",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether the user's eligibility address is required to be 'covered by the City' to be eligible. 'City coverage' is always True for addresses within the GMA, otherwise it's determined by the Get FoCo administrators.",
            ),
        ),
        migrations.AlterField(
            model_name="iqprogramrd",
            name="requires_is_in_gma",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether the user's eligibility address is required to be in the GMA to be eligible.",
            ),
        ),
    ]
