# Generated by Django 4.1.8 on 2024-07-24 22:51

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

from app.models import (
    User,
    Address,
    AddressRD,
    Household,
    HouseholdMembers,
    EligibilityProgram,
    EligibilityProgramRD,
    IQProgram,
    IQProgramRD,
    Feedback,
    AppAdmin,
)


def apply_admin_group(apps, schema_editor):
    # Define the auth group. Note that this migration will override the
    # permissions if a group exists with this name
    admin_group, _ = Group.objects.get_or_create(name='admin_program')

    # Determine if there's an issue getting a Permission object (only for this
    # function, as it's first to run). This is due to Django migrations
    # [possibly] not entirely completing the previous model rename; instructions
    # to the user are included if the error is captured
    try:
        # Define the list of permissions (based on testing)
        permissions_list = [
            Permission.objects.get(
                codename='change_user',
                content_type=ContentType.objects.get_for_model(User),
            ),
            Permission.objects.get(
                codename='view_user',
                content_type=ContentType.objects.get_for_model(User),
            ),
            Permission.objects.get(
                codename='view_appadmin',
                content_type=ContentType.objects.get_for_model(AppAdmin),
            ),
            Permission.objects.get(
                codename='change_appadmin',
                content_type=ContentType.objects.get_for_model(AppAdmin),
            ),
            Permission.objects.get(
                codename='view_address',
                content_type=ContentType.objects.get_for_model(Address),
            ),
            Permission.objects.get(
                codename='change_addressrd',
                content_type=ContentType.objects.get_for_model(AddressRD),
            ),
            Permission.objects.get(
                codename='view_addressrd',
                content_type=ContentType.objects.get_for_model(AddressRD),
            ),
            Permission.objects.get(
                codename='change_household',
                content_type=ContentType.objects.get_for_model(Household),
            ),
            Permission.objects.get(
                codename='view_household',
                content_type=ContentType.objects.get_for_model(Household),
            ),
            Permission.objects.get(
                codename='view_householdmembers',
                content_type=ContentType.objects.get_for_model(HouseholdMembers),
            ),
            Permission.objects.get(
                codename='change_eligibilityprogram',
                content_type=ContentType.objects.get_for_model(EligibilityProgram),
            ),
            Permission.objects.get(
                codename='view_eligibilityprogram',
                content_type=ContentType.objects.get_for_model(EligibilityProgram),
            ),
            Permission.objects.get(
                codename='add_eligibilityprogramrd',
                content_type=ContentType.objects.get_for_model(EligibilityProgramRD),
            ),
            Permission.objects.get(
                codename='change_eligibilityprogramrd',
                content_type=ContentType.objects.get_for_model(EligibilityProgramRD),
            ),
            Permission.objects.get(
                codename='view_eligibilityprogramrd',
                content_type=ContentType.objects.get_for_model(EligibilityProgramRD),
            ),
            Permission.objects.get(
                codename='view_iqprogram',
                content_type=ContentType.objects.get_for_model(IQProgram),
            ),
            Permission.objects.get(
                codename='add_iqprogramrd',
                content_type=ContentType.objects.get_for_model(IQProgramRD),
            ),
            Permission.objects.get(
                codename='change_iqprogramrd',
                content_type=ContentType.objects.get_for_model(IQProgramRD),
            ),
            Permission.objects.get(
                codename='view_iqprogramrd',
                content_type=ContentType.objects.get_for_model(IQProgramRD),
            ),
            Permission.objects.get(
                codename='view_feedback',
                content_type=ContentType.objects.get_for_model(Feedback),
            ),
            Permission.objects.get(
                codename='delete_eligibilityprogram',
                content_type=ContentType.objects.get_for_model(EligibilityProgram),
            ),
        ]

    except Permission.DoesNotExist:
        # The specific case for this error is found: instruct the user as to the
        # workaround
        print(
            "\n\n\n\nDjango didn't finalize the previous migration properly.",
            "To resolve, run the following commands in sequence:",
            "\n\npython manage.py migrate app 0036",
            "\npython manage.py migrate",
            "\n\nThe message after the first command may show 'No migrations to apply',",
            "but the proper finalization will have occurred.\n\n\n"
        )
        raise Exception(
            "Permission error occurred: see message above the stack trace (in 'Running migrations:') for remediation"
        )

    # Set the permissions for the group
    admin_group.permissions.set(permissions_list)


def apply_income_group(apps, schema_editor):
    # Define the auth group. Note that this migration will override the
    # permissions if a group exists with this name
    income_group, _ = Group.objects.get_or_create(name='income_verification_staff')

    # Define the list of permissions (from testing)
    permissions_list = [
        Permission.objects.get(
            codename='change_user',
            content_type=ContentType.objects.get_for_model(User),
        ),
        Permission.objects.get(
            codename='view_user',
            content_type=ContentType.objects.get_for_model(User),
        ),
        Permission.objects.get(
            codename='view_appadmin',
            content_type=ContentType.objects.get_for_model(AppAdmin),
        ),
        Permission.objects.get(
            codename='change_appadmin',
            content_type=ContentType.objects.get_for_model(AppAdmin),
        ),
        Permission.objects.get(
            codename='view_address',
            content_type=ContentType.objects.get_for_model(Address),
        ),
        Permission.objects.get(
            codename='change_addressrd',
            content_type=ContentType.objects.get_for_model(AddressRD),
        ),
        Permission.objects.get(
            codename='view_addressrd',
            content_type=ContentType.objects.get_for_model(AddressRD),
        ),
        Permission.objects.get(
            codename='view_eligibilityprogram',
            content_type=ContentType.objects.get_for_model(EligibilityProgram),
        ),
        Permission.objects.get(
            codename='change_household',
            content_type=ContentType.objects.get_for_model(Household),
        ),
        Permission.objects.get(
            codename='view_household',
            content_type=ContentType.objects.get_for_model(Household),
        ),
        Permission.objects.get(
            codename='view_householdmembers',
            content_type=ContentType.objects.get_for_model(HouseholdMembers),
        ),
        Permission.objects.get(
            codename='view_iqprogram',
            content_type=ContentType.objects.get_for_model(IQProgram),
        ),
    ]

    # Set the permissions for the group
    income_group.permissions.set(permissions_list)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0036_rename_admin_appadmin"),
    ]

    operations = [
        # Define no operation for reversion. Removing permissions groups will
        # reset all applied users, so the 'apply' procedures instead overwrite
        # permissions on any existing groups
        migrations.RunPython(apply_admin_group, migrations.RunPython.noop),
        migrations.RunPython(apply_income_group, migrations.RunPython.noop),
    ]
