[project]
name = "Get-Your"
version = "7.4.0"
description = "Platform for Get-Your income-qualified program universal application"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "django~=4.2.30",
    "django-environ~=0.13.0",
    "django-json-widget~=2.1.1",
    "django-phonenumber-field[phonenumbers]~=8.4.0",
    "django-q2~=1.10.0",
    "django-redis~=6.0.0",
    "django-storages[azure]~=1.14.6",
    "gunicorn~=26.0.0",
    "hiredis~=3.3.1",
    "httpagentparser~=1.9.9",
    "pandas~=3.0.3",
    "pendulum~=3.2.0",
    "psycopg2-binary~=2.9.12",
    "python-magic~=0.4.27",
    "python-magic-bin~=0.4.14 ; (platform_machine == 'x86_64' and sys_platform == 'darwin') or sys_platform == 'win32'",
    "redis~=8.0.0",
    "rich~=15.0.0",
    "sendgrid~=6.12.5",
    "tomlkit~=0.15.0",
    "twilio~=9.10.9",
    "usaddress~=0.5.16",
    "whitenoise~=6.12.0",
]
