# Generated by Django 4.2.23 on 2025-09-03 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import get_your.users.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usernotes', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('awaiting_user_response', models.BooleanField(default=False, help_text='Designates that the admin is waiting for a user to respond to a request made separate from this platform. This is used only to filter income-verification applicants.')),
                ('internal_notes', models.TextField(blank=True, help_text='Notes pertaining to this user, for internal use. This field is not visible to applicants.')),
            ],
            options={
                'verbose_name': 'user note',
                'verbose_name_plural': 'user notes',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='has_viewed_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_action_notification_at',
            field=models.DateTimeField(blank=True, help_text='The latest time a notification was sent because of or requesting user action.', null=True, verbose_name='Last user action notification'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_completed_at',
            field=models.DateTimeField(blank=True, help_text='The latest time the user completed an application/renewal.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_application_status',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_has_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=get_your.users.fields.LowerEmailModelField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
