# Generated by Django 4.2.23 on 2025-09-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0002_applicationpage'),
        ('users', '0002_usernote_remove_user_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_application_status',
        ),
        migrations.AddField(
            model_name='user',
            name='user_completed_pages',
            field=models.ManyToManyField(related_name='user', to='ref.applicationpage'),
        ),
    ]
