# Generated by Django 4.1.8 on 2023-11-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("logger_name", models.CharField(max_length=100)),
                (
                    "log_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "NotSet"),
                            (20, "Info"),
                            (30, "Warning"),
                            (10, "Debug"),
                            (40, "Error"),
                            (50, "Fatal"),
                        ],
                        db_index=True,
                    ),
                ),
                ("message", models.TextField()),
                ("trace", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Logging",
                "verbose_name_plural": "Logging",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LevelsRD",
            fields=[
                ("name", models.CharField(max_length=20)),
                (
                    "level",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
