# Generated by Django 4.1.8 on 2023-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0003_populate_levelrd"),
    ]

    operations = [
        migrations.AddField(
            model_name="detail",
            name="app_name",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="detail",
            name="process_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="detail",
            name="thread_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="detail",
            name="log_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "NotSet"),
                    (20, "Info"),
                    (30, "Warning"),
                    (10, "Debug"),
                    (40, "Error"),
                    (50, "Fatal"),
                ]
            ),
        ),
        migrations.AddIndex(
            model_name="detail",
            index=models.Index(
                fields=["process_id", "thread_id"], name="process_thread_idx"
            ),
        ),
    ]
