# Generated by Django 4.1.8 on 2023-12-04 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0010_alter_detail_log_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detail",
            name="lineno",
        ),
    ]
