# Generated by Django 4.1.8 on 2023-12-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0011_remove_detail_lineno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="process_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="detail",
            name="thread_id",
            field=models.CharField(max_length=100),
        ),
    ]
