# Generated by Django 4.1.8 on 2023-12-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0012_alter_detail_process_id_alter_detail_thread_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="process_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="detail",
            name="thread_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
