# Generated by Django 4.2.23 on 2025-09-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='is_updated',
            new_name='user_has_updated',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='is_updated',
            new_name='user_has_updated',
        ),
        migrations.RenameField(
            model_name='householdmembers',
            old_name='is_updated',
            new_name='user_has_updated',
        ),
    ]
