# Generated by Django 4.2.23 on 2025-10-20 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_is_updated_address_user_has_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='number_persons_in_household',
        ),
        migrations.RemoveField(
            model_name='householdmembers',
            name='household_info',
        ),
        migrations.AddField(
            model_name='householdmembers',
            name='birthdate',
            field=models.DateField(default=datetime.date(1, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='householdmembers',
            name='full_name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='householdmembers',
            name='identification_path',
            field=models.FileField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
