# Generated by Django 5.2.7 on 2026-01-20 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_household_number_persons_in_household_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdmembers',
            name='user',
        ),
        migrations.AddField(
            model_name='householdmembers',
            name='household',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.household'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='householdmembers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
