# Generated by Django 4.1 on 2023-05-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_user_options_remove_user_created_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="addressrd",
            name="unq_full_address",
        ),
        migrations.AlterField(
            model_name="addressrd",
            name="address_sha1",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
