# Generated by Django 4.1.8 on 2023-06-08 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_remove_address_is_eligibility_address_updated_and_more"),
        (
            "app",
            "0009_rename_ami_range_max_household_income_as_fraction_of_ami_and_more",
        ),
    ]

    operations = []
