# Generated by Django 4.1.8 on 2023-06-08 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_merge_20230608_0945"),
    ]

    operations = [
        migrations.RenameField(
            model_name="iqprogramrd",
            old_name="autoapply_ami_threshold",
            new_name="enable_autoapply",
        ),
    ]
