# Generated by Django 4.1.8 on 2023-07-20 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_rename_autoapply_ami_threshold_iqprogramrd_enable_autoapply"),
    ]

    operations = [
        migrations.AddField(
            model_name="iqprogram",
            name="has_renewed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_renewal_action",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_renewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="IQProgramHist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("historical_values", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="iqprogram_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EligibilityProgramHist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("historical_values", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="eligibility_program_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
