# Generated by Django 4.1.8 on 2023-12-26 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_remove_iqprogram_has_renewed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="iqprogramrd",
            old_name="renewal_interval",
            new_name="renewal_interval_month",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="renewal_email_sent_at",
            new_name="last_action_notification_at",
        ),
    ]
