# Generated by Django 4.1.8 on 2024-02-20 19:55

import pendulum

from django.db import migrations

from django_q.models import Schedule

OLD_SCHEDULE_NAME = 'Send Renewal Email'
NEW_SCHEDULE_NAME = 'Run Renewal Task'

def apply_migration(apps, schema_editor):
    # Remove the previous 'Send Renewal Email' schedule before adding the new one
    Schedule.objects.filter(name=OLD_SCHEDULE_NAME).delete()

    # Add daily 'Run Renewal Task' schedule to Django-Q2
    Schedule.objects.create(
        # Name the schedule
        name=NEW_SCHEDULE_NAME,
        # Run the function
        func='app.tasks.run_renewal_task',
        # Create a 'daily' schedule
        schedule_type=Schedule.DAILY,
        # Call the cluster specified by the Q_CLUSTER setting
        cluster='DjangORM',
        # DOES NOT REPEAT. This needs to be 'enabled' once online (generally by
        # setting repeats=-1 to repeat forever)
        repeats=0,
        # Set the next run to be 1 second after midnight in America/Denver
        # timezone, starting today (from whenever this is applied). Note that
        # this should be in the past, adding to this not running by default
        next_run=pendulum.today(tz='America/Denver').add(seconds=1),
    )


def revert_migration(apps, schema_editor):
    # Remove the schedule with the same name
    Schedule.objects.filter(name=NEW_SCHEDULE_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_add_django_q_renewal_schedule"),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
