# Generated by Django 4.1.8 on 2024-03-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_change_django_q_renewal_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iqprogramrd',
            old_name='renewal_interval_month',
            new_name='renewal_interval_year',
        ),
    ]
