# Generated by Django 4.1.8 on 2024-04-22 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "app",
            "0020_alter_address_options_alter_addressrd_options_and_more_squashed_0030_alter_permissions_group",
        ),
        ("app", "0020_merge_20240421_0832"),
    ]

    operations = []
