# Generated by Django 4.1.8 on 2024-06-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0032_alter_addressrd_address1_alter_addressrd_address2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressrd",
            name="is_city_covered",
            field=models.BooleanField(
                default=None,
                help_text="Designates whether an address is eligible for benefits. This can be altered by administrators if the address is outside the GMA.",
                null=True,
            ),
        ),
    ]
