# Generated by Django 4.1.8 on 2024-07-24 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0034_alter_iqprogramrd_friendly_supplemental_info"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Admin",
            new_name="AppAdmin",
        ),
    ]
