# Generated by Django 4.2.23 on 2025-09-03 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.backend


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ref', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_usernote_remove_user_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_updated', models.BooleanField(default=False)),
                ('is_income_verified', models.BooleanField(default=False, help_text='Designates whether an applicant has had their income verified.', verbose_name='income has been verified')),
                ('duration_at_address', models.CharField(choices=[('More than 3 Years', 'More than 3 Years'), ('1 to 3 Years', '1 to 3 Years'), ('Less than a Year', 'Less than a Year')], max_length=200)),
                ('number_persons_in_household', models.IntegerField(default=1, help_text='Number of persons in the household.', verbose_name='household size')),
                ('income_as_fraction_of_ami', models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True)),
                ('rent_own', models.CharField(choices=[('rent', 'Rent'), ('own', 'Own')], help_text='Designates whether the applicant rents or owns their primary residence.', max_length=200, verbose_name='rent or own')),
            ],
            options={
                'verbose_name': 'household',
                'verbose_name_plural': 'household',
            },
        ),
        migrations.CreateModel(
            name='HouseholdMembers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('household_info', models.JSONField(blank=True, null=True)),
                ('is_updated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'household member',
                'verbose_name_plural': 'household members',
            },
        ),
        migrations.CreateModel(
            name='IQProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_at', models.DateTimeField(null=True)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='iq_programs', to='ref.iqprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iq_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user IQ program',
                'verbose_name_plural': 'user IQ programs',
            },
        ),
        migrations.CreateModel(
            name='EligibilityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('document_path', models.FileField(default=None, max_length=5000, null=True, upload_to=files.backend.userfiles_path)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ref.eligibilityprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user eligibility program',
                'verbose_name_plural': 'user eligibility programs',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_updated', models.BooleanField(default=False)),
                ('eligibility_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eligibility_user', to='ref.address')),
                ('mailing_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ref.address')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
