# Generated by Django 6.0.5 on 2026-05-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_household_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdmembers',
            name='user_has_updated',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
