# Generated by Django 6.0.5 on 2026-05-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_householdmembers_user_has_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iqprogram',
            name='is_enrolled',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
