# Generated by Django 4.1.8 on 2023-11-30 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LevelsRD",
            new_name="LevelRD",
        ),
    ]
