# Generated by Django 4.1.8 on 2023-11-30 21:03

from django.db import migrations
from logger.models import LevelRD

from logger.constants import LOG_LEVELS


def apply_migration(apps, schema_editor):
    LevelRD.objects.bulk_create([
        LevelRD(
            name=x[1],
            level=x[0],
            ) for x in LOG_LEVELS
    ])


def revert_migration(apps, schema_editor):
    LevelRD.objects.filter(
        name__in=[x[1] for x in LOG_LEVELS]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0002_rename_levelsrd_levelrd"),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
