# Generated by Django 4.1.8 on 2023-11-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0005_alter_detail_app_name_alter_detail_trace"),
    ]

    operations = [
        migrations.AddField(
            model_name="detail",
            name="lineno",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
