# Generated by Django 4.1.8 on 2023-12-04 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0007_detail_module_name_detail_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detail",
            old_name="module_name",
            new_name="function",
        ),
    ]
