# Generated by Django 4.1.8 on 2023-12-04 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0008_rename_module_name_detail_function"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="log_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="detail",
                to="logger.levelrd",
            ),
        ),
    ]
