# Generated by Django 4.1.8 on 2023-12-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0009_alter_detail_log_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="log_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "NotSet"),
                    (20, "Info"),
                    (30, "Warning"),
                    (10, "Debug"),
                    (40, "Error"),
                    (50, "Fatal"),
                ]
            ),
        ),
    ]
