# Generated by Django 4.1.8 on 2023-12-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0014_detail_has_been_addressed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="has_been_addressed",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
