# Generated by Django 4.1.8 on 2024-03-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0001_squashed_0016_migrate_from_log_to_logger"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detail",
            options={"verbose_name": "log", "verbose_name_plural": "logs"},
        ),
        migrations.AlterField(
            model_name="detail",
            name="log_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "NotSet"),
                    (20, "Info"),
                    (30, "Warning"),
                    (10, "Debug"),
                    (40, "Error"),
                    (50, "Fatal"),
                ],
                db_index=True,
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="logger_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="detail",
            name="user_id",
            field=models.PositiveBigIntegerField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="detail",
            index=models.Index(
                fields=["thread_id", "user_id"], name="logger_det_thread_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detail",
            index=models.Index(
                fields=["logger_name", "user_id"], name="logger_det_logger_user_idx"
            ),
        ),
    ]
