# Generated by Django 4.1.8 on 2026-07-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_squashed_0016_migrate_from_log_to_logger'),
    ]

    operations = [
        migrations.CreateModel(
            name='USPSAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('process_id', models.CharField(db_index=True, max_length=100)),
                ('thread_id', models.CharField(db_index=True, max_length=100)),
                ('function', models.CharField(max_length=50, null=True)),
                ('user_id', models.PositiveBigIntegerField(null=True)),
                ('message', models.TextField()),
                ('trace', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'USPS Audit Logging',
                'verbose_name_plural': 'USPS Audit Logging',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='uspsaudit',
            index=models.Index(fields=['process_id', 'thread_id'], name='logger_usps_process_712f94_idx'),
        ),
    ]
