# Generated by Django 4.2.23 on 2025-09-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogLevel',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('level', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('process_id', models.CharField(db_index=True, max_length=100)),
                ('thread_id', models.CharField(db_index=True, max_length=100)),
                ('app_name', models.CharField(db_index=True, max_length=20)),
                ('logger_name', models.CharField(max_length=100)),
                ('log_level', models.PositiveSmallIntegerField(choices=[(0, 'NotSet'), (20, 'Info'), (30, 'Warning'), (10, 'Debug'), (40, 'Error'), (50, 'Fatal')])),
                ('function', models.CharField(max_length=50, null=True)),
                ('user_id', models.PositiveBigIntegerField(null=True)),
                ('message', models.TextField()),
                ('trace', models.TextField(blank=True)),
                ('has_been_addressed', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Logging',
                'verbose_name_plural': 'Logging',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['process_id', 'thread_id'], name='monitor_log_process_deaa85_idx')],
            },
        ),
    ]
