# Generated by Django 5.2.7 on 2025-11-05 19:36

import pendulum

from django.db import migrations

from django_q.models import Schedule

RUN_TASK_NAME = "Run Renewal Task"
POPULATE_CACHE_NAME = "Populate Renewal Cache"


def apply_populate_cache(apps, schema_editor):
    # Add daily "Populate Renewal Cache" schedule to Django-Q2
    Schedule.objects.create(
        # Name the schedule
        name=POPULATE_CACHE_NAME,
        # Run the function
        func="runner.tasks.populate_redis_cache",
        # Create a "daily" schedule
        schedule_type=Schedule.DAILY,
        # Call the cluster specified by the Q_CLUSTER setting
        cluster="DJRedis",
        # DOES NOT REPEAT. This needs to be "enabled" once online (generally by
        # setting repeats=-1 to repeat forever)
        repeats=0,
        # Set the next run to be at just before midnight yesterday in
        # America/Denver timezone (should continue to be just before the "Run
        # Renewal Task" schedule)
        next_run=pendulum.yesterday(tz="America/Denver").add(
            hours=23,
            minutes=30,
        ),
    )


def revert_populate_cache(apps, schema_editor):
    # Remove the schedule with the same name
    Schedule.objects.filter(name=POPULATE_CACHE_NAME).delete()


def apply_renewal_task(apps, schema_editor):
    # Add daily "Run Renewal Task" schedule to Django-Q2
    Schedule.objects.create(
        # Name the schedule
        name=RUN_TASK_NAME,
        # Run the function
        func="runner.tasks.run_renewal_task",
        # Create a "daily" schedule
        schedule_type=Schedule.DAILY,
        # Call the cluster specified by the Q_CLUSTER setting
        cluster="DJRedis",
        # DOES NOT REPEAT. This needs to be "enabled" once online (generally by
        # setting repeats=-1 to repeat forever)
        repeats=0,
        # Set the next run to be 30 minutes after midnight in America/Denver
        # timezone, starting today (from whenever this is applied). Note that
        # this is in the past and therefore will not run (with `repeats=0`)
        next_run=pendulum.today(tz="America/Denver").add(minutes=30),
    )


def revert_renewal_task(apps, schema_editor):
    # Remove the schedule with the same name
    Schedule.objects.filter(name=RUN_TASK_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(apply_populate_cache, revert_populate_cache),
        migrations.RunPython(apply_renewal_task, revert_renewal_task),
    ]
