# Generated by Django 4.1.8 on 2024-03-07 19:46

from django.db import migrations, models
from logger.models import LevelRD

from logger.constants import LOG_LEVELS


def apply_levelrd_items(apps, schema_editor):
    LevelRD.objects.bulk_create([
        LevelRD(
            name=x[1],
            level=x[0],
            ) for x in LOG_LEVELS
    ])


def revert_levelrd_items(apps, schema_editor):
    LevelRD.objects.filter(
        name__in=[x[1] for x in LOG_LEVELS]
    ).delete()


class Migration(migrations.Migration):

    replaces = [('logger', '0001_initial'), ('logger', '0002_rename_levelsrd_levelrd'), ('logger', '0003_populate_levelrd'), ('logger', '0004_detail_app_name_detail_process_id_detail_thread_id_and_more'), ('logger', '0005_alter_detail_app_name_alter_detail_trace'), ('logger', '0006_detail_lineno'), ('logger', '0007_detail_module_name_detail_user_id'), ('logger', '0008_rename_module_name_detail_function'), ('logger', '0009_alter_detail_log_level'), ('logger', '0010_alter_detail_log_level'), ('logger', '0011_remove_detail_lineno'), ('logger', '0012_alter_detail_process_id_alter_detail_thread_id'), ('logger', '0013_alter_detail_process_id_alter_detail_thread_id'), ('logger', '0014_detail_has_been_addressed'), ('logger', '0015_alter_detail_has_been_addressed'), ('logger', '0016_migrate_from_log_to_logger')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('logger_name', models.CharField(max_length=100)),
                ('log_level', models.PositiveSmallIntegerField(choices=LOG_LEVELS)),
                ('message', models.TextField()),
                ('trace', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Logging',
                'verbose_name_plural': 'Logging',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LevelRD',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('level', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RunPython(
            code=apply_levelrd_items,
            reverse_code=apply_levelrd_items,
        ),
        migrations.AddField(
            model_name='detail',
            name='app_name',
            field=models.CharField(db_index=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='process_id',
            field=models.CharField(db_index=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='thread_id',
            field=models.CharField(db_index=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='detail',
            index=models.Index(fields=['process_id', 'thread_id'], name='logger_det_process_712f94_idx'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='trace',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='user_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='function',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='has_been_addressed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
