# Generated by Django 3.1.3 on 2021-02-17 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.user')),
                ('address', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(default='Fort Collins', max_length=64)),
                ('state', models.CharField(default='CO', max_length=2)),
                ('zipCode', models.DecimalField(decimal_places=0, max_digits=5)),
                ('n2n', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.user')),
                ('married', models.BooleanField()),
                ('dependents', models.IntegerField(verbose_name=100)),
                ('grossAnnualHouseholdIncome', models.CharField(choices=[('Below $30,000', 'Below $30,000'), ('$30,000 ~ $60,000', '$30,000 ~ $60,000'), ('Over $60,000', 'Over $60,000')], default='Below $30,000', max_length=20)),
                ('snap', models.BooleanField()),
                ('freeReducedLunch', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
