# Generated by Django 3.1.3 on 2021-02-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='programs',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.user')),
                ('snap', models.BooleanField()),
                ('freeReducedLunch', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='eligibility',
            old_name='married',
            new_name='rent',
        ),
        migrations.RemoveField(
            model_name='eligibility',
            name='freeReducedLunch',
        ),
        migrations.RemoveField(
            model_name='eligibility',
            name='snap',
        ),
        migrations.AlterField(
            model_name='addresses',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='zipCode',
            field=models.DecimalField(decimal_places=0, default='', max_digits=5),
        ),
    ]
