# Generated by Django 3.1.3 on 2021-03-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210301_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibility',
            name='rent',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Own', 'Own')], max_length=10),
        ),
    ]
