# Generated by Django 3.1.3 on 2021-03-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_user_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='zipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('zipCode', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
