# Generated by Django 3.1.7 on 2021-03-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_user_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibility',
            name='qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='grossAnnualHouseholdIncome',
            field=models.CharField(choices=[('Below $19,800', 'Below $19,800'), ('$19,800 ~ $32,800', '$19,800 ~ $32,800'), ('Over $32,800', 'Over $32,800')], default='Below $19,800', max_length=20),
        ),
    ]
