# Generated by Django 3.1.7 on 2021-03-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210323_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='sanitizedCity',
            field=models.CharField(blank=True, default='Fort Collins', max_length=64),
        ),
        migrations.AddField(
            model_name='addresses',
            name='sanitizedState',
            field=models.CharField(blank=True, default='CO', max_length=2),
        ),
        migrations.AddField(
            model_name='addresses',
            name='sanitizedZipCode',
            field=models.DecimalField(blank=True, decimal_places=0, default='00000', max_digits=5),
        ),
        migrations.AddField(
            model_name='addresses',
            name='santizedAddress',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='addresses',
            name='santizedAddress2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
