# Generated by Django 3.1.7 on 2021-03-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20210331_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='sanitizedCity',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='sanitizedState',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
