# Generated by Django 3.1.7 on 2021-03-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20210331_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='sanitizedZipCode',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5),
        ),
    ]
