# Generated by Django 3.1.7 on 2021-03-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20210331_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='sanitizedState',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
