# Generated by Django 3.1.7 on 2021-03-31 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20210331_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='santizedAddress',
            new_name='sanitizedAddress',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='santizedAddress2',
            new_name='sanitizedAddress2',
        ),
    ]
