# Generated by Django 3.1.3 on 2021-04-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_futureemails'),
        ('application', '0014_auto_20210331_0213'),
    ]

    operations = [
    ]
