# Generated by Django 3.1.7 on 2021-04-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20210331_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibility',
            name='grossAnnualHouseholdIncome',
            field=models.CharField(choices=[('Below $19,800', 'Below $19,800'), ('$19,800 ~ $32,800', '$19,800 ~ $32,800'), ('Over $32,800', 'Over $32,800'), ('+1,000,000', '+1,000,000')], default='Below $19,800', max_length=20),
        ),
    ]
