# Generated by Django 3.1.3 on 2021-04-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_merge_20210408_1625'),
        ('application', '0015_auto_20210407_1211'),
    ]

    operations = [
    ]
