# Generated by Django 3.1.7 on 2021-04-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_futureemails'),
        ('application', '0015_auto_20210407_1211'),
    ]

    operations = [
    ]
