# Generated by Django 3.1.7 on 2021-04-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_merge_20210408_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='Tax1040',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
