# Generated by Django 3.1.7 on 2021-04-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_remove_programs_tax1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eligibility',
            old_name='qualified',
            new_name='DEqualified',
        ),
        migrations.AddField(
            model_name='eligibility',
            name='GRqualified',
            field=models.BooleanField(default=False),
        ),
    ]
