# Generated by Django 3.1.3 on 2021-04-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_remove_programs_tax1040'),
        ('application', '0016_merge_20210408_1650'),
    ]

    operations = [
    ]
