# Generated by Django 3.1.3 on 2021-04-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_merge_20210412_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='sanitizedZipCode',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=5),
        ),
    ]
