# Generated by Django 3.1.3 on 2021-04-13 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20210412_1533'),
        ('application', '0022_auto_20210411_2301'),
    ]

    operations = [
    ]
