# Generated by Django 3.1.3 on 2021-04-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_merge_20210412_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='sanitizedAddress',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='sanitizedAddress2',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='sanitizedCity',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='sanitizedState',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='sanitizedZipCode',
        ),
    ]
