# Generated by Django 3.1.7 on 2021-04-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20210412_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='Testing',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
