# Generated by Django 3.1.7 on 2021-04-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_programs_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='Testing',
        ),
        migrations.AddField(
            model_name='programs',
            name='Identification',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
