# Generated by Django 3.1.7 on 2021-04-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_auto_20210424_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='Identification',
        ),
    ]
