# Generated by Django 3.1.7 on 2021-05-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_remove_programs_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='Identification',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programs',
            name='Utility',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
