# Generated by Django 3.1.7 on 2021-05-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_auto_20210504_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='addressVerification',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.user')),
                ('Identification', models.BooleanField()),
                ('Utility', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='programs',
            name='Identification',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='Utility',
        ),
    ]
