# Generated by Django 3.1.7 on 2021-05-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_auto_20210504_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressverification',
            name='Identification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addressverification',
            name='Utility',
            field=models.BooleanField(default=False),
        ),
    ]
