# Generated by Django 3.1.7 on 2021-05-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_auto_20210504_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressverification',
            name='Identification',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='addressverification',
            name='Utility',
            field=models.BooleanField(),
        ),
    ]
