# Generated by Django 3.1.7 on 2021-05-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20210506_2245'),
        ('application', '0031_auto_20210506_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_files',
            field=models.ManyToManyField(related_name='residencyforms', to='dashboard.residencyForm'),
        ),
    ]
