# Generated by Django 3.1.7 on 2021-05-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_user_address_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibility',
            name='RecreationQualified',
            field=models.BooleanField(default=False),
        ),
    ]
