# Generated by Django 3.1.7 on 2021-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0033_eligibility_recreationqualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressverification',
            name='freeReducedLunch',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
