# Generated by Django 3.1.7 on 2021-07-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_addresslookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='hasConnexion',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='isInGMA',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
