# Generated by Django 3.1.7 on 2021-07-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_auto_20210720_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='n2n',
        ),
    ]
