# Generated by Django 3.1.7 on 2021-07-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_remove_addresses_n2n'),
    ]

    operations = [
        migrations.DeleteModel(
            name='zipCode',
        ),
    ]
