# Generated by Django 3.1.7 on 2021-08-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_delete_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibility',
            name='dependentsAge',
            field=models.IntegerField(default=0, verbose_name=100),
        ),
    ]
