# Generated by Django 3.1.7 on 2021-08-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_attestations'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureemails',
            name='connexionCommunication',
            field=models.BooleanField(default=False),
        ),
    ]
