# Generated by Django 3.1.7 on 2021-09-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_auto_20210824_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='Identification',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
