# Generated by Django 3.1.7 on 2021-09-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_programs_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressverification',
            name='Identification',
        ),
        migrations.RemoveField(
            model_name='addressverification',
            name='freeReducedLunch',
        ),
    ]
