# Generated by Django 3.1.7 on 2021-09-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_auto_20210908_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futureemails',
            name='email',
        ),
        migrations.AlterField(
            model_name='futureemails',
            name='connexionCommunication',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
