# Generated by Django 3.1.7 on 2021-09-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_auto_20210916_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibility',
            name='ConnexionQualified',
            field=models.CharField(default='RESETME', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eligibility',
            name='GenericQualified',
            field=models.CharField(default='RESETME', max_length=20),
            preserve_default=False,
        ),
    ]
