# Generated by Django 3.1.7 on 2021-09-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_auto_20210916_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='form1040',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
