# Generated by Django 3.1.7 on 2021-09-23 19:05

from django.db import migrations, models
import django.db.models.deletion

def add_ami_data(apps, schema_editor):
    AMI = apps.get_model('application', 'AMI')

    AMI.objects.create(householdNum=1, ami=65900, active=1)
    AMI.objects.create(householdNum=2, ami=75300, active=1)
    AMI.objects.create(householdNum=3, ami=84700, active=1)
    AMI.objects.create(householdNum=4, ami=94100, active=1)
    AMI.objects.create(householdNum=5, ami=101700, active=1)
    AMI.objects.create(householdNum=6, ami=109200, active=1)
    AMI.objects.create(householdNum=7, ami=116700, active=1)
    AMI.objects.create(householdNum=8, ami=124300, active=1)

def add_iq_data(apps, schema_editor):
    IQ = apps.get_model('application', 'iqProgramQualifications')

    IQ.objects.create(name='connexion', percentAmi=0.3)
    IQ.objects.create(name='grocery', percentAmi=0.5)
    IQ.objects.create(name='recreation', percentAmi=0.3)


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_programs_form1040'), 
    ]

    operations = [
        migrations.CreateModel(
            name='AMI',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('householdNum', models.IntegerField(primary_key=True, serialize=False, verbose_name=100)),
                ('active', models.BooleanField()),
                ('ami', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(add_ami_data),
        migrations.CreateModel(
            name='iqProgramQualifications',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('percentAmi', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(add_iq_data),
        migrations.AlterField(
            model_name='eligibility',
            name='grossAnnualHouseholdIncome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='dependents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='application.ami'),
        ),
        migrations.AddField(
            model_name='eligibility',
            name='AmiRange_max',
            field=models.DecimalField(decimal_places=4, default=-1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eligibility',
            name='AmiRange_min',
            field=models.DecimalField(decimal_places=4, default=-1, max_digits=5),
            preserve_default=False,
        ),
    ]
