# Generated by Django 3.1.7 on 2021-09-27 20:34

from django.db import migrations, models

def add_ami_data(apps, schema_editor):
    AMI = apps.get_model('application', 'AMI')

    AMI.objects.create(householdNum='Each Additional', ami=4480, active=1)


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_auto_20210927_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ami',
            name='householdNum',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.RunPython(add_ami_data),
        migrations.AlterField(
            model_name='eligibility',
            name='dependents',
            field=models.IntegerField(default=1, verbose_name=100),
        ),
    ]
