# Generated by Django 3.1.7 on 2021-09-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_alter_ami_20210927_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligibility',
            name='dependentsAge',
        ),
        migrations.AddField(
            model_name='eligibility',
            name='dependentsBirthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
