# Generated by Django 3.1.7 on 2021-09-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0050_auto_20210929_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibility',
            name='dependentsFirstName',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eligibility',
            name='dependentsLastName',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
