# Generated by Django 3.1.7 on 2021-10-07 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_auto_20210929_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligibility',
            name='dependentsBirthdate',
        ),
        migrations.RemoveField(
            model_name='eligibility',
            name='dependentsFirstName',
        ),
        migrations.RemoveField(
            model_name='eligibility',
            name='dependentsLastName',
        ),
        migrations.CreateModel(
            name='MoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dependent', models.IntegerField()),
                ('dependentsBirthdate', models.DateField(blank=True, null=True)),
                ('dependentsName', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
