# Generated by Django 3.1.7 on 2021-10-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0054_moreinfo_dependentinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreinfo',
            name='dependent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moreinfo',
            name='dependentsBirthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moreinfo',
            name='dependentsName',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
