# Generated by Django 3.1.7 on 2021-10-27 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0055_auto_20211021_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moreinfo',
            name='dependent',
        ),
    ]
