# Generated by Django 3.1.7 on 2021-11-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0056_remove_moreinfo_dependent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moreinfo',
            name='dependentsBirthdate',
        ),
        migrations.RemoveField(
            model_name='moreinfo',
            name='dependentsName',
        ),
    ]
