# Generated by Django 3.1.7 on 2022-01-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0057_auto_20211110_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
