# Generated by Django 3.1.7 on 2022-01-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0058_auto_20220114_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
    ]
