# Generated by Django 3.1.7 on 2022-03-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0062_add_is_archived_admin_field_20220207_1002'),
        ('application', '0060_programs_ebb_acf'),
    ]

    operations = [
    ]
