# Generated by Django 3.1.7 on 2022-06-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0064_moreinfo_last4ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinfo',
            name='last4SSN',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
