# Generated by Django 3.1.7 on 2022-06-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0065_auto_20220611_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinfo',
            name='last4SSN',
            field=models.IntegerField(blank=True, max_length=9999, null=True),
        ),
    ]
