# Generated by Django 3.1.7 on 2022-06-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0066_auto_20220611_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moreinfo',
            name='last4SSN',
        ),
    ]
