# Generated by Django 3.1.7 on 2022-06-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0067_remove_moreinfo_last4ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibility',
            name='rent',
            field=models.CharField(choices=[('More than 3 Years', 'More than 3 Years'), ('1 to 3 Years', '1 to 3 Years'), ('Less than a Year', 'Less than a Year')], max_length=200),
        ),
    ]
