# Generated by Django 3.1.7 on 2022-07-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0068_auto_20220630_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='leap',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
