# Generated by Django 3.1.7 on 2022-07-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0069_programs_leap'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibility',
            name='SPINQualified',
            field=models.CharField(default='NULL', max_length=20),
            preserve_default=False,
        ),
    ]
