# Generated by Django 3.1.7 on 2022-09-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0070_eligibility_spinqualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
