# Generated by Django 3.1.7 on 2023-02-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0071_addresses_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_viewed_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
