# Generated by Django 3.1.7 on 2023-01-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0071_addresses_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibility',
            name='spin_privacy_acknowledgement',
            field=models.BooleanField(default=False),
        ),
    ]
