# Generated by Django 3.1.7 on 2023-01-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0072_programs_medicaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='form1040',
            field=models.BooleanField(default=False),
        ),
    ]
