# Generated by Django 3.1.7 on 2023-02-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0073_auto_20230129_1603'),
        ('application', '0072_eligibility_spin_privacy_acknowledgement'),
    ]

    operations = [
    ]
