# Generated by Django 3.1.7 on 2023-03-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0074_merge_20230208_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibility',
            name='SpinAccessQualified_depr',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        # Copy the SPINQualified data into the new field for posterity. RunSQL.noop removes this statement from unapply, if migrations are rolled back.
        migrations.RunSQL(
            """UPDATE public.application_eligibility SET "SpinAccessQualified_depr"="SPINQualified" """,
            migrations.RunSQL.noop,
        ),
        # "Remove" (mark unused) values of SPINQualified that have a False privacy acknowledgment value (meaning that the user hasn't been through the new SPIN's workflow). RunSQL.noop removes this statement from unapply, if migrations are rolled back.
        migrations.RunSQL(
            """UPDATE public.application_eligibility SET "SPINQualified"='' WHERE spin_privacy_acknowledgement=False""",
            migrations.RunSQL.noop,
        ),
    ]
