# Generated by Django 3.1.7 on 2023-02-17 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0072_user_has_viewed_dashboard'),
        ('application', '0074_merge_20230208_1101'),
    ]

    operations = [
    ]
