# Generated by Django 3.1.7 on 2023-03-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0076_eligibilityhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligibilityhistory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='eligibilityhistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eligibility_history', to='application.user'),
            preserve_default=False,
        ),
    ]
