# Generated by Django 3.1.7 on 2023-03-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0077_auto_20230321_0813'),
        ('application', '0075_eligibility_spinaccessqualified_depr'),
    ]

    operations = [
    ]
