# Generated by Django 3.1.7 on 2023-03-28 00:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0078_merge_20230327_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdMembers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.user')),
                ('household_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at_init_temp', models.DateTimeField(null=True)),
                ('modified_at_init_temp', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
