# Generated by Django 3.1.3 on 2021-03-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='document_title',
            field=models.CharField(choices=[('SNAP', 'SNAP'), ('Free and Reduced Lunch', 'Free and Reduced Lunch')], max_length=30),
        ),
    ]
