# Generated by Django 3.1.7 on 2021-03-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='starRating',
            field=models.TextField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
