# Generated by Django 3.1.7 on 2021-04-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_form_taxbox1amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='TaxBox1Amount',
            new_name='TaxBoxAmount',
        ),
    ]
