# Generated by Django 3.1.7 on 2021-04-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210405_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='TaxBoxAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
