# Generated by Django 3.1.3 on 2021-04-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210322_1522'),
        ('dashboard', '0007_auto_20210405_1153'),
    ]

    operations = [
    ]
