# Generated by Django 3.1.7 on 2021-04-07 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20210407_1211'),
        ('dashboard', '0008_auto_20210406_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxInformation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.user')),
                ('TaxBoxAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
