# Generated by Django 3.1.7 on 2021-04-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210322_1522'),
        ('dashboard', '0009_taxinformation'),
    ]

    operations = [
    ]
