# Generated by Django 3.1.3 on 2021-04-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_merge_20210408_1625'),
        ('dashboard', '0009_taxinformation'),
    ]

    operations = [
    ]
