# Generated by Django 3.1.7 on 2021-04-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_merge_20210408_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='TaxBoxAmount',
        ),
    ]
