# Generated by Django 3.1.3 on 2021-04-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210409_0011'),
        ('dashboard', '0010_merge_20210408_1650'),
    ]

    operations = [
    ]
