# Generated by Django 3.1.7 on 2021-05-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_residencyform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencyform',
            name='document_title',
            field=models.CharField(choices=[('Identification', 'Identification'), ('Utility', 'Utility')], max_length=30),
        ),
    ]
