# Generated by Django 3.1.7 on 2021-09-17 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20210907_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='document',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
    ]
