# Generated by Django 3.1.7 on 2021-09-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210917_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='document_title',
            field=models.CharField(choices=[('SNAP', 'SNAP'), ('Free and Reduced Lunch', 'Free and Reduced Lunch'), ('1040 Form', '1040 Form'), ('Identification', 'Identification')], max_length=30),
        ),
    ]
