# Generated by Django 3.1.7 on 2021-12-15 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20210924_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='document',
            field=models.FileField(upload_to='mobileVers/uploads/2021-12-15/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
    ]
