# Generated by Django 3.1.7 on 2021-12-15 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20211215_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencyform',
            name='document',
            field=models.FileField(upload_to='mobileVers/uploads/2021-12-15/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
    ]
