# Generated by Django 3.1.7 on 2021-12-21 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20211215_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='document',
            field=models.FileField(max_length=5000, upload_to='mobileVers/uploads/2021-12-21/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='residencyform',
            name='document',
            field=models.FileField(max_length=5000, upload_to='mobileVers/uploads/2021-12-21/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
    ]
