# Generated by Django 3.1.7 on 2022-01-12 02:32

import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20220111_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencyform',
            name='document',
            field=models.FileField(max_length=5000, upload_to=dashboard.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
    ]
