# Generated by Django 3.1.7 on 2022-06-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20220203_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinformation',
            name='last4SSN',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
