# Generated by Django 3.1.7 on 2022-06-22 21:14

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_taxinformation_last4ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='document',
            field=models.FileField(max_length=5000, upload_to=dashboard.models.user_directory_path),
        ),
    ]
