# Generated by Django 3.1.7 on 2022-06-23 17:37

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20220622_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencyform',
            name='document',
            field=models.FileField(max_length=5000, upload_to=dashboard.models.user_directory_path),
        ),
    ]
