# Generated by Django 3.1.7 on 2022-07-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20220706_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='document_title',
            field=models.CharField(choices=[('SNAP', 'SNAP'), ('Free and Reduced Lunch', 'Free and Reduced Lunch'), ('1040 Form', '1040 Form'), ('Identification', 'Identification'), ('ACP Letter', 'ACP Letter'), ('LEAP Letter', 'LEAP Letter')], max_length=30),
        ),
    ]
