services:
  docs:
    image: get_your_local_docs
    container_name: get_your_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./get_your:/app/get_your:z
    ports:
      - '9000:9000'
    command: /start-docs
