# Generated by Django 5.2.7 on 2026-01-21 23:04

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import get_your.users.managers
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_usernote_remove_user_name_user_first_name_and_more'), ('users', '0003_remove_user_user_application_status_and_more'), ('users', '0004_alter_user_options_alter_user_email_and_more')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ref', '0002_applicationpage'),
        ('ref', '0004_iqprogram_additional_external_form_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='first name')),
                ('has_viewed_dashboard', models.BooleanField(default=False)),
                ('last_action_notification_at', models.DateTimeField(blank=True, help_text='The latest time a notification was sent because of or requesting user action.', null=True, verbose_name='Last user action notification')),
                ('last_completed_at', models.DateTimeField(blank=True, help_text='The latest time the user completed an application/renewal.', null=True)),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='last name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('user_has_updated', models.BooleanField(default=False)),
                ('user_completed_pages', models.ManyToManyField(related_name='user', to='ref.applicationpage')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', get_your.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usernotes', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('awaiting_user_response', models.BooleanField(default=False, help_text='Designates that the admin is waiting for a user to respond to a request made separate from this platform. This is used only to filter income-verification applicants.')),
                ('internal_notes', models.TextField(blank=True, help_text='Notes pertaining to this user, for internal use. This field is not visible to applicants.')),
            ],
            options={
                'verbose_name': 'user note',
                'verbose_name_plural': 'user notes',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_ci_uniqueness'),
        ),
    ]
