# Generated by Django 6.0.5 on 2026-05-21 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0004_iqprogram_additional_external_form_link_and_more'),
        ('users', '0005_user_is_archived_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='duration_at_address',
            field=models.CharField(choices=[('More than 3 Years', 'More than 3 Years'), ('1 to 3 Years', '1 to 3 Years'), ('Less than a Year', 'Less than a Year')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='eligibility_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eligibility_user', to='ref.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='income_as_fraction_of_ami',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_income_verified',
            field=models.BooleanField(default=False, help_text='Designates whether an applicant has had their income verified.', verbose_name='income has been verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='mailing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ref.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='rent_own',
            field=models.CharField(choices=[('rent', 'Rent'), ('own', 'Own')], default='', help_text='Designates whether the applicant rents or owns their primary residence.', max_length=200, verbose_name='rent or own'),
        ),
    ]
