# Generated by Django 6.0.5 on 2026-05-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_duration_at_address_user_eligibility_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='duration_at_address',
            field=models.CharField(choices=[('More than 3 Years', 'More than 3 Years'), ('1 to 3 Years', '1 to 3 Years'), ('Less than a Year', 'Less than a Year')], db_default='', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_viewed_dashboard',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(db_default=False, default=False, help_text="Designates whether the user is marked as 'archived'."),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_income_verified',
            field=models.BooleanField(db_default=False, default=False, help_text='Designates whether an applicant has had their income verified.', verbose_name='income has been verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rent_own',
            field=models.CharField(choices=[('rent', 'Rent'), ('own', 'Own')], db_default='', default='', help_text='Designates whether the applicant rents or owns their primary residence.', max_length=200, verbose_name='rent or own'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_has_updated',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='usernote',
            name='awaiting_user_response',
            field=models.BooleanField(db_default=False, default=False, help_text='Designates that the admin is waiting for a user to respond to a request made separate from this platform. This is used only to filter income-verification applicants.'),
        ),
    ]
